In [123]:
# Creating Taining Set
import numpy as np
import pandas as pd

df = pd.read_csv('Iris.csv')
original_data = df.iloc[:,:4]


In [124]:
df

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

## Step-1: Scaling

In [125]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

df.iloc[:,0:4] = scaler.fit_transform(df.iloc[:,0:4])
df.head(5)

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0      -0.900681      1.032057      -1.341272     -1.312977  Iris-setosa
1      -1.143017     -0.124958      -1.341272     -1.312977  Iris-setosa
2      -1.385353      0.337848      -1.398138     -1.312977  Iris-setosa
3      -1.506521      0.106445      -1.284407     -1.312977  Iris-setosa
4      -1.021849      1.263460      -1.341272     -1.312977  Iris-setosa

## Step-2: Covariance Matrix

In [126]:
Cov_mat = np.cov( [ df.iloc[:,0],df.iloc[:,1],df.iloc[:,2],df.iloc[:,3] ] )
Cov_mat

array([[ 1.00671141, -0.11010327,  0.87760486,  0.82344326],
       [-0.11010327,  1.00671141, -0.42333835, -0.358937  ],
       [ 0.87760486, -0.42333835,  1.00671141,  0.96921855],
       [ 0.82344326, -0.358937  ,  0.96921855,  1.00671141]])

## Step-3: Eigenval and Eigenvectors

In [127]:
eigenval,eigenvec = np.linalg.eig(Cov_mat)

In [128]:
eigenval

array([2.93035378, 0.92740362, 0.14834223, 0.02074601])

In [129]:
eigenvec

array([[ 0.52237162, -0.37231836, -0.72101681,  0.26199559],
       [-0.26335492, -0.92555649,  0.24203288, -0.12413481],
       [ 0.58125401, -0.02109478,  0.14089226, -0.80115427],
       [ 0.56561105, -0.06541577,  0.6338014 ,  0.52354627]])

## This is the real :: for ith row = ith eigenvalue

In [130]:
eigenvec.T 

array([[ 0.52237162, -0.26335492,  0.58125401,  0.56561105],
       [-0.37231836, -0.92555649, -0.02109478, -0.06541577],
       [-0.72101681,  0.24203288,  0.14089226,  0.6338014 ],
       [ 0.26199559, -0.12413481, -0.80115427,  0.52354627]])

### Get Largest Values

In [131]:
PC_1_2 = eigenvec.T[:2]
PC_1_2

array([[ 0.52237162, -0.26335492,  0.58125401,  0.56561105],
       [-0.37231836, -0.92555649, -0.02109478, -0.06541577]])

## Step-4: Transform Data into Reduced Dimension

In [132]:
transpose_PC = PC_1_2.T
transpose_PC

array([[ 0.52237162, -0.37231836],
       [-0.26335492, -0.92555649],
       [ 0.58125401, -0.02109478],
       [ 0.56561105, -0.06541577]])

In [133]:
Transformed = np.dot(original_data,transpose_PC)

new_df = pd.DataFrame(Transformed,columns=['PC1','PC2'])
new_df['Species'] = df['Species']
new_df

PC1       PC2         Species
0    2.669231 -5.180887     Iris-setosa
1    2.696434 -4.643645     Iris-setosa
2    2.481163 -4.752183     Iris-setosa
3    2.571512 -4.626615     Iris-setosa
4    2.590658 -5.236211     Iris-setosa
..        ...       ...             ...
145  7.033251 -5.531352  Iris-virginica
146  6.613485 -4.889261  Iris-virginica
147  6.759094 -5.437263  Iris-virginica
148  6.782974 -5.719634  Iris-virginica
149  6.274423 -5.198680  Iris-virginica

[150 rows x 3 columns]